### ISSUE TITLE
Scatter function error inside utils file

### ISSUE THREAD

**Issue by gjkaur** [Artur112/Brats2019#3]
2020-05-17 07:22:58.417980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    masks = expand_as_one_hot(masks, n_classes)
  File "/content/drive/My Drive/Artur/model_utils/utils.py", line 426, in expand_as_one_hot
    return torch.zeros(shape).to(input.device).scatter_(1, input, longx)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index' in call to _th_scatter_

**Comment by Artur112** [comment]
Does my latest commit fix it? Please note this code is old and has many issues. I have a better repo coming soon.
